services:
  prometheus:
    image: docker.bbqq.pl:8666/bbqq-prometheus
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  
  blackbox_exporter:
    image: docker.bbqq.pl:8666/bbqq-blackbox_exporter
    ports:
      - 9115:9115

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=TwojeHaslo # change this
    ports:
      - 8001:3000
    depends_on:
      - prometheus

  speedtest_cli:
    image: docker.bbqq.pl:8666/bbqq-speedtest
    environment:
      SPEEDTEST_INTERVAL: "1200"
    depends_on:
      - prometheus
      - pushgateway

volumes:
  grafana-storage:
