global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['pushgateway:9091']
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets:
        - '8.8.8.8'  # SAMPLE TARGETS
        - '1.1.1.1'
        - 'wp.pl'
        - 'yahoo.com'
        - 'google.com'
        - '192.168.1.1'
        - '192.168.5.1'
        - '192.168.5.6'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115'
